# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=14)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_to', to='exchange.Currency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exchange',
            unique_together=set([('date', 'currency_from', 'currency_to')]),
        ),
    ]
